export const email = "blues9524@gmail.com"
export const github = "https://github.com/shaurya9524"
export const discord = "https://discord.com/users/893705256368750592"
export const linkedin = "https://linkedin.com/in/shaurya-chauhan-119b3526b"
export const siteUrl = "https://shauryadev.in"
export const twitter = "https://x.com/Shaurya9524"
export const discordServer = "https://discord.gg/7gtXphYbPq"
